keep only two envs

diff --git a/.github/workflows/provision-infrastructure.yml b/.github/workflows/provision-infrastructure.yml
--- a/.github/workflows/provision-infrastructure.yml
+++ b/.github/workflows/provision-infrastructure.yml
@@ -51,7 +51,7 @@ jobs:
         run: echo "TF_STATE_KEY=state-pr-${{ github.event.pull_request.number }}.tfstate" >> $GITHUB_ENV
 
       - name: Terraform Init and Plan Development
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         run: |
           terraform init \
             -backend-config="region=${{ vars.AWS_REGION }}" \
@@ -62,18 +62,18 @@ jobs:
 
       - name: Terraform Apply Development
         id: apply-step
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         continue-on-error: true
         run: terraform apply -auto-approve
 
       - name: Terraform Destroy on Failure
         if: steps.apply-step.outcome == 'failure'
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         run: |
           echo "Terraform apply failed. Starting destroy to clean up."
           terraform destroy -auto-approve
 
-  terraform-environments-staging:
+  terraform-environments-production:
     name: Terraform Environments
     runs-on: ubuntu-latest
     permissions:
@@ -82,7 +82,7 @@ jobs:
 
     if: github.ref == 'refs/heads/main'
     env:
-      TF_VAR_environment: "staging"
+      TF_VAR_environment: "production"
       TF_VAR_region: eu-central-1
       TF_VAR_aws_account_id: 746669194690
     steps:
@@ -109,70 +109,6 @@ jobs:
 
       - name: Delete KMS Alias (if exists)
         run: |
-          if aws kms describe-alias --alias-name alias/eks/termin-eks-staging > /dev/null 2>&1; then
-            echo "Deleting existing KMS alias..."
-            aws kms delete-alias --alias-name alias/eks/termin-eks-staging
-          else
-            echo "KMS alias does not exist. Skipping deletion."
-          fi
-
-      - name: Terraform Format
-        run: terraform fmt -check
-
-      - name: Terraform Validate
-        run: terraform validate
-      
-      - name: Terraform Init and Plan Staging
-        working-directory: infrastructure/environments/general
-        run: |
-          terraform init \
-            -backend-config="region=eu-central-1" \
-            -backend-config="bucket=terraform-state-terminapp" \
-            -backend-config="key=state.tfstate" \
-            -backend-config="use_lockfile=true"
-          terraform plan
-        
-      - name: Terraform Apply Staging
-        id: apply-step
-        working-directory: infrastructure/environments/general
-        continue-on-error: true
-        run: terraform apply -auto-approve
-
-      - name: Terraform Destroy on Failure
-        if: steps.apply-step.outcome == 'failure'
-        working-directory: infrastructure/environments/general
-        run: |
-          echo "Terraform apply failed. Starting destroy to clean up."
-          terraform destroy -auto-approve
-      
-      - name: Fail the Pipeline
-        if: steps.apply-step.outcome == 'failure'
-        run: |
-          echo "Terraform apply failed. Cleanup complete. Marking job as failed."
-          exit 1
-
-  terraform-environments-production:
-    name: Terraform Environments
-    runs-on: ubuntu-latest
-    environment: production
-    if: github.event_name == 'release'
-    env:
-      AWS_REGION: ${{ vars.AWS_REGION }}
-      TF_VAR_environment: "production"
-      TF_VAR_region: ${{ vars.AWS_REGION }}
-      TF_VAR_aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.11.2
-          terraform_wrapper: false
-      
-      - name: Delete KMS Alias (if exists)
-        run: |
           if aws kms describe-alias --alias-name alias/eks/termin-eks-production > /dev/null 2>&1; then
             echo "Deleting existing KMS alias..."
             aws kms delete-alias --alias-name alias/eks/termin-eks-production
@@ -185,26 +121,32 @@ jobs:
 
       - name: Terraform Validate
         run: terraform validate
-
+      
       - name: Terraform Init and Plan Production
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         run: |
           terraform init \
-            -backend-config="region=${{ vars.AWS_REGION }}" \
-            -backend-config="bucket=${{ vars.s3_bucket_name }}" \
+            -backend-config="region=eu-central-1" \
+            -backend-config="bucket=terraform-state-terminapp" \
             -backend-config="key=state.tfstate" \
             -backend-config="use_lockfile=true"
           terraform plan
-
+        
       - name: Terraform Apply Production
         id: apply-step
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         continue-on-error: true
         run: terraform apply -auto-approve
 
       - name: Terraform Destroy on Failure
         if: steps.apply-step.outcome == 'failure'
-        working-directory: infrastructure/environments/general
+        working-directory: infrastructure/entry
         run: |
           echo "Terraform apply failed. Starting destroy to clean up."
           terraform destroy -auto-approve
+      
+      - name: Fail the Pipeline
+        if: steps.apply-step.outcome == 'failure'
+        run: |
+          echo "Terraform apply failed. Cleanup complete. Marking job as failed."
+          exit 1
